/*
 * Copyright (c) 2015 Cryptonomex, Inc., and contributors.
 *
 * The MIT License
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#include <enudex/chain/get_config.hpp>
#include <enudex/chain/config.hpp>
#include <enudex/chain/protocol/types.hpp>

namespace enudex { namespace chain {

fc::variant_object get_config()
{
   fc::mutable_variant_object result;

   result[ "ENUDEX_SYMBOL" ] = ENUDEX_SYMBOL;
   result[ "ENUDEX_ADDRESS_PREFIX" ] = ENUDEX_ADDRESS_PREFIX;
   result[ "ENUDEX_MIN_ACCOUNT_NAME_LENGTH" ] = ENUDEX_MIN_ACCOUNT_NAME_LENGTH;
   result[ "ENUDEX_MAX_ACCOUNT_NAME_LENGTH" ] = ENUDEX_MAX_ACCOUNT_NAME_LENGTH;
   result[ "ENUDEX_MIN_ASSET_SYMBOL_LENGTH" ] = ENUDEX_MIN_ASSET_SYMBOL_LENGTH;
   result[ "ENUDEX_MAX_ASSET_SYMBOL_LENGTH" ] = ENUDEX_MAX_ASSET_SYMBOL_LENGTH;
   result[ "ENUDEX_MAX_SHARE_SUPPLY" ] = ENUDEX_MAX_SHARE_SUPPLY;
   result[ "ENUDEX_MAX_PAY_RATE" ] = ENUDEX_MAX_PAY_RATE;
   result[ "ENUDEX_MAX_SIG_CHECK_DEPTH" ] = ENUDEX_MAX_SIG_CHECK_DEPTH;
   result[ "ENUDEX_MIN_TRANSACTION_SIZE_LIMIT" ] = ENUDEX_MIN_TRANSACTION_SIZE_LIMIT;
   result[ "ENUDEX_MIN_BLOCK_INTERVAL" ] = ENUDEX_MIN_BLOCK_INTERVAL;
   result[ "ENUDEX_MAX_BLOCK_INTERVAL" ] = ENUDEX_MAX_BLOCK_INTERVAL;
   result[ "ENUDEX_DEFAULT_BLOCK_INTERVAL" ] = ENUDEX_DEFAULT_BLOCK_INTERVAL;
   result[ "ENUDEX_DEFAULT_MAX_TRANSACTION_SIZE" ] = ENUDEX_DEFAULT_MAX_TRANSACTION_SIZE;
   result[ "ENUDEX_DEFAULT_MAX_BLOCK_SIZE" ] = ENUDEX_DEFAULT_MAX_BLOCK_SIZE;
   result[ "ENUDEX_DEFAULT_MAX_TIME_UNTIL_EXPIRATION" ] = ENUDEX_DEFAULT_MAX_TIME_UNTIL_EXPIRATION;
   result[ "ENUDEX_DEFAULT_MAINTENANCE_INTERVAL" ] = ENUDEX_DEFAULT_MAINTENANCE_INTERVAL;
   result[ "ENUDEX_DEFAULT_MAINTENANCE_SKIP_SLOTS" ] = ENUDEX_DEFAULT_MAINTENANCE_SKIP_SLOTS;
   result[ "ENUDEX_MIN_UNDO_HISTORY" ] = ENUDEX_MIN_UNDO_HISTORY;
   result[ "ENUDEX_MAX_UNDO_HISTORY" ] = ENUDEX_MAX_UNDO_HISTORY;
   result[ "ENUDEX_MIN_BLOCK_SIZE_LIMIT" ] = ENUDEX_MIN_BLOCK_SIZE_LIMIT;
   result[ "ENUDEX_MIN_TRANSACTION_EXPIRATION_LIMIT" ] = ENUDEX_MIN_TRANSACTION_EXPIRATION_LIMIT;
   result[ "ENUDEX_BLOCKCHAIN_PRECISION" ] = ENUDEX_BLOCKCHAIN_PRECISION;
   result[ "ENUDEX_BLOCKCHAIN_PRECISION_DIGITS" ] = ENUDEX_BLOCKCHAIN_PRECISION_DIGITS;
   result[ "ENUDEX_DEFAULT_TRANSFER_FEE" ] = ENUDEX_DEFAULT_TRANSFER_FEE;
   result[ "ENUDEX_MAX_INSTANCE_ID" ] = ENUDEX_MAX_INSTANCE_ID;
   result[ "ENUDEX_100_PERCENT" ] = ENUDEX_100_PERCENT;
   result[ "ENUDEX_1_PERCENT" ] = ENUDEX_1_PERCENT;
   result[ "ENUDEX_MAX_MARKET_FEE_PERCENT" ] = ENUDEX_MAX_MARKET_FEE_PERCENT;
   result[ "ENUDEX_DEFAULT_FORCE_SETTLEMENT_DELAY" ] = ENUDEX_DEFAULT_FORCE_SETTLEMENT_DELAY;
   result[ "ENUDEX_DEFAULT_FORCE_SETTLEMENT_OFFSET" ] = ENUDEX_DEFAULT_FORCE_SETTLEMENT_OFFSET;
   result[ "ENUDEX_DEFAULT_FORCE_SETTLEMENT_MAX_VOLUME" ] = ENUDEX_DEFAULT_FORCE_SETTLEMENT_MAX_VOLUME;
   result[ "ENUDEX_DEFAULT_PRICE_FEED_LIFETIME" ] = ENUDEX_DEFAULT_PRICE_FEED_LIFETIME;
   result[ "ENUDEX_MAX_FEED_PRODUCERS" ] = ENUDEX_MAX_FEED_PRODUCERS;
   result[ "ENUDEX_DEFAULT_MAX_AUTHORITY_MEMBERSHIP" ] = ENUDEX_DEFAULT_MAX_AUTHORITY_MEMBERSHIP;
   result[ "ENUDEX_DEFAULT_MAX_ASSET_WHITELIST_AUTHORITIES" ] = ENUDEX_DEFAULT_MAX_ASSET_WHITELIST_AUTHORITIES;
   result[ "ENUDEX_DEFAULT_MAX_ASSET_FEED_PUBLISHERS" ] = ENUDEX_DEFAULT_MAX_ASSET_FEED_PUBLISHERS;
   result[ "ENUDEX_COLLATERAL_RATIO_DENOM" ] = ENUDEX_COLLATERAL_RATIO_DENOM;
   result[ "ENUDEX_MIN_COLLATERAL_RATIO" ] = ENUDEX_MIN_COLLATERAL_RATIO;
   result[ "ENUDEX_MAX_COLLATERAL_RATIO" ] = ENUDEX_MAX_COLLATERAL_RATIO;
   result[ "ENUDEX_DEFAULT_MAINTENANCE_COLLATERAL_RATIO" ] = ENUDEX_DEFAULT_MAINTENANCE_COLLATERAL_RATIO;
   result[ "ENUDEX_DEFAULT_MAX_SHORT_SQUEEZE_RATIO" ] = ENUDEX_DEFAULT_MAX_SHORT_SQUEEZE_RATIO;
   result[ "ENUDEX_DEFAULT_MARGIN_PERIOD_SEC" ] = ENUDEX_DEFAULT_MARGIN_PERIOD_SEC;
   result[ "ENUDEX_DEFAULT_MAX_WITNESSES" ] = ENUDEX_DEFAULT_MAX_WITNESSES;
   result[ "ENUDEX_DEFAULT_MAX_COMMITTEE" ] = ENUDEX_DEFAULT_MAX_COMMITTEE;
   result[ "ENUDEX_DEFAULT_MAX_PROPOSAL_LIFETIME_SEC" ] = ENUDEX_DEFAULT_MAX_PROPOSAL_LIFETIME_SEC;
   result[ "ENUDEX_DEFAULT_COMMITTEE_PROPOSAL_REVIEW_PERIOD_SEC" ] = ENUDEX_DEFAULT_COMMITTEE_PROPOSAL_REVIEW_PERIOD_SEC;
   result[ "ENUDEX_DEFAULT_NETWORK_PERCENT_OF_FEE" ] = ENUDEX_DEFAULT_NETWORK_PERCENT_OF_FEE;
   result[ "ENUDEX_DEFAULT_LIFETIME_REFERRER_PERCENT_OF_FEE" ] = ENUDEX_DEFAULT_LIFETIME_REFERRER_PERCENT_OF_FEE;
   result[ "ENUDEX_DEFAULT_MAX_BULK_DISCOUNT_PERCENT" ] = ENUDEX_DEFAULT_MAX_BULK_DISCOUNT_PERCENT;
   result[ "ENUDEX_DEFAULT_BULK_DISCOUNT_THRESHOLD_MIN" ] = ENUDEX_DEFAULT_BULK_DISCOUNT_THRESHOLD_MIN;
   result[ "ENUDEX_DEFAULT_BULK_DISCOUNT_THRESHOLD_MAX" ] = ENUDEX_DEFAULT_BULK_DISCOUNT_THRESHOLD_MAX;
   result[ "ENUDEX_DEFAULT_CASHBACK_VESTING_PERIOD_SEC" ] = ENUDEX_DEFAULT_CASHBACK_VESTING_PERIOD_SEC;
   result[ "ENUDEX_DEFAULT_CASHBACK_VESTING_THRESHOLD" ] = ENUDEX_DEFAULT_CASHBACK_VESTING_THRESHOLD;
   result[ "ENUDEX_DEFAULT_BURN_PERCENT_OF_FEE" ] = ENUDEX_DEFAULT_BURN_PERCENT_OF_FEE;
   result[ "ENUDEX_WITNESS_PAY_PERCENT_PRECISION" ] = ENUDEX_WITNESS_PAY_PERCENT_PRECISION;
   result[ "ENUDEX_DEFAULT_MAX_ASSERT_OPCODE" ] = ENUDEX_DEFAULT_MAX_ASSERT_OPCODE;
   result[ "ENUDEX_DEFAULT_FEE_LIQUIDATION_THRESHOLD" ] = ENUDEX_DEFAULT_FEE_LIQUIDATION_THRESHOLD;
   result[ "ENUDEX_DEFAULT_ACCOUNTS_PER_FEE_SCALE" ] = ENUDEX_DEFAULT_ACCOUNTS_PER_FEE_SCALE;
   result[ "ENUDEX_DEFAULT_ACCOUNT_FEE_SCALE_BITSHIFTS" ] = ENUDEX_DEFAULT_ACCOUNT_FEE_SCALE_BITSHIFTS;
   result[ "ENUDEX_MAX_WORKER_NAME_LENGTH" ] = ENUDEX_MAX_WORKER_NAME_LENGTH;
   result[ "ENUDEX_MAX_URL_LENGTH" ] = ENUDEX_MAX_URL_LENGTH;
   result[ "ENUDEX_NEAR_SCHEDULE_CTR_IV" ] = ENUDEX_NEAR_SCHEDULE_CTR_IV;
   result[ "ENUDEX_FAR_SCHEDULE_CTR_IV" ] = ENUDEX_FAR_SCHEDULE_CTR_IV;
   result[ "ENUDEX_CORE_ASSET_CYCLE_RATE" ] = ENUDEX_CORE_ASSET_CYCLE_RATE;
   result[ "ENUDEX_CORE_ASSET_CYCLE_RATE_BITS" ] = ENUDEX_CORE_ASSET_CYCLE_RATE_BITS;
   result[ "ENUDEX_DEFAULT_WITNESS_PAY_PER_BLOCK" ] = ENUDEX_DEFAULT_WITNESS_PAY_PER_BLOCK;
   result[ "ENUDEX_DEFAULT_WITNESS_PAY_VESTING_SECONDS" ] = ENUDEX_DEFAULT_WITNESS_PAY_VESTING_SECONDS;
   result[ "ENUDEX_DEFAULT_WORKER_BUDGET_PER_DAY" ] = ENUDEX_DEFAULT_WORKER_BUDGET_PER_DAY;
   result[ "ENUDEX_MAX_INTEREST_APR" ] = ENUDEX_MAX_INTEREST_APR;
   result[ "ENUDEX_COMMITTEE_ACCOUNT" ] = ENUDEX_COMMITTEE_ACCOUNT;
   result[ "ENUDEX_WITNESS_ACCOUNT" ] = ENUDEX_WITNESS_ACCOUNT;
   result[ "ENUDEX_RELAXED_COMMITTEE_ACCOUNT" ] = ENUDEX_RELAXED_COMMITTEE_ACCOUNT;
   result[ "ENUDEX_NULL_ACCOUNT" ] = ENUDEX_NULL_ACCOUNT;
   result[ "ENUDEX_TEMP_ACCOUNT" ] = ENUDEX_TEMP_ACCOUNT;

   return result;
}

} } // enudex::chain
